CREATE DATABASE airflow;
CREATE USER airflow WITH ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;

CREATE DATABASE hive_metastore;
CREATE USER hive WITH ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE hive_metastore TO hive;
